mod helpers;
mod test_resolver_simple_lookup_srv_multiple;
mod test_resolver_simple_lookup_srv_single;
mod test_trivial_with_default_config;

pub use test_resolver_simple_lookup_srv_multiple::TEST_RESOLVER_SIMPLE_LOOKUP_SRV_MULTIPLE;
pub use test_resolver_simple_lookup_srv_single::TEST_RESOLVER_SIMPLE_LOOKUP_SRV_SINGLE;
pub use test_trivial_with_default_config::TEST_TRIVIAL_WITH_DEFAULT_CONFIG;
